module.exports = {
url: "https://alpha.yoodlize.com/",
elements: {
SearchField: 'input[placeholder="Search for an item"]',
Menu:'#basic-nav-dropdown > div > img',
Profile: '#rebass-provider > div > div.sc-bsbRJL.kgtuDL.sc-bwzfXH.dszAdl.sc-bdVaJa.isrEgr > div > div.sc-bsbRJL.kgtuDL.sc-bwzfXH.kmMPxk.sc-bdVaJa.QeDJw > div:nth-child(1) > a:nth-child(5) > div',
List: '#rebass-provider > div > div.sc-bsbRJL.kgtuDL.sc-bwzfXH.dszAdl.sc-bdVaJa.isrEgr > div > div.sc-bsbRJL.kgtuDL.sc-bwzfXH.kmMPxk.sc-bdVaJa.QeDJw > div:nth-child(1) > a:nth-child(4) > div',
Login: '#rebass-provider > div > div.Home-root-1avl7 > div > div.sc-kIPQKe.dxbYcN > div.Header-root-O9oW9 > div > nav > div > div.navbar-collapse.collapse > div.sc-bdVaJa.kmtHOY > div > ul > li:nth-child(4) > a > div > span',
User: 'input[name="email"]',
Pass: 'input[name="password"]',
Submit: 'button[type="submit"]',
SeachLink: '#rebass-provider > div > div.Home-root-1avl7 > div > div.sc-kIPQKe.dxbYcN > div.Header-root-O9oW9 > div > nav > div > div.navbar-collapse.collapse > div.sc-bdVaJa.kmtHOY > div > ul > li:nth-child(2) > a > div',
Advanced: 'div[class="sc-jqCOkK NqsLm sc-gqjmRU SUbM"]',
Clothing: '#rebass-provider > div > div.Search-root-2gThI > div > div.Search-searchResultContainer-33ivj > div:nth-child(1) > div.sc-bwzfXH.hFUbDu.sc-bdVaJa.eekvlW > div:nth-child(2) > div.sc-bwzfXH.liBCIH.sc-bdVaJa.eGpriy > div:nth-child(1) > div.icheckbox_minimal-blue > ins',
Tag:'#rebass-provider > div > div.Search-root-2gThI > div > div.Search-searchResultContainer-33ivj > div:nth-child(1) > div > div.mb-l.sc-bdVaJa.iHZvIS > div',
Home: '#rebass-provider > div > div.Search-root-2gThI > div > div.Search-searchResultContainer-33ivj > div:nth-child(1) > div.sc-bwzfXH.hFUbDu.sc-bdVaJa.eekvlW > div:nth-child(2) > div.sc-bwzfXH.liBCIH.sc-bdVaJa.eGpriy > div:nth-child(3) > div.icheckbox_minimal-blue > ins',
Electronics: '#rebass-provider > div > div.Search-root-2gThI > div > div.Search-searchResultContainer-33ivj > div:nth-child(1) > div.sc-bwzfXH.hFUbDu.sc-bdVaJa.eekvlW > div:nth-child(2) > div.sc-bwzfXH.liBCIH.sc-bdVaJa.eGpriy > div:nth-child(5) > div.icheckbox_minimal-blue > ins',
Toys: '#rebass-provider > div > div.Search-root-2gThI > div > div.Search-searchResultContainer-33ivj > div:nth-child(1) > div.sc-bwzfXH.hFUbDu.sc-bdVaJa.eekvlW > div:nth-child(2) > div.sc-bwzfXH.liBCIH.sc-bdVaJa.eGpriy > div:nth-child(7) > div.icheckbox_minimal-blue > ins',
Business: '#rebass-provider > div > div.Search-root-2gThI > div > div.Search-searchResultContainer-33ivj > div:nth-child(1) > div.sc-bwzfXH.hFUbDu.sc-bdVaJa.eekvlW > div:nth-child(2) > div.sc-bwzfXH.liBCIH.sc-bdVaJa.eGpriy > div:nth-child(9) > div.icheckbox_minimal-blue > ins',
Recreations: '#rebass-provider > div > div.Search-root-2gThI > div > div.Search-searchResultContainer-33ivj > div:nth-child(1) > div.sc-bwzfXH.hFUbDu.sc-bdVaJa.eekvlW > div:nth-child(2) > div.sc-bwzfXH.liBCIH.sc-bdVaJa.eGpriy > div:nth-child(11) > div.icheckbox_minimal-blue > ins',
Lawn: '#rebass-provider > div > div.Search-root-2gThI > div > div.Search-searchResultContainer-33ivj > div:nth-child(1) > div.sc-bwzfXH.hFUbDu.sc-bdVaJa.eekvlW > div:nth-child(2) > div.sc-bwzfXH.liBCIH.sc-bdVaJa.eGpriy > div:nth-child(13) > div.icheckbox_minimal-blue > ins',
Misc: '#rebass-provider > div > div.Search-root-2gThI > div > div.Search-searchResultContainer-33ivj > div:nth-child(1) > div.sc-bwzfXH.hFUbDu.sc-bdVaJa.eekvlW > div:nth-child(2) > div.sc-bwzfXH.liBCIH.sc-bdVaJa.eGpriy > div:nth-child(15) > div.icheckbox_minimal-blue > ins',
Sporting: '#rebass-provider > div > div.Search-root-2gThI > div > div.Search-searchResultContainer-33ivj > div:nth-child(1) > div.sc-bwzfXH.hFUbDu.sc-bdVaJa.eekvlW > div:nth-child(2) > div.sc-bwzfXH.liBCIH.sc-bdVaJa.eGpriy > div:nth-child(2) > div.icheckbox_minimal-blue > ins',
Outdoor: '#rebass-provider > div > div.Search-root-2gThI > div > div.Search-searchResultContainer-33ivj > div:nth-child(1) > div.sc-bwzfXH.hFUbDu.sc-bdVaJa.eekvlW > div:nth-child(2) > div.sc-bwzfXH.liBCIH.sc-bdVaJa.eGpriy > div:nth-child(4) > div.icheckbox_minimal-blue > ins',
Tools: '#rebass-provider > div > div.Search-root-2gThI > div > div.Search-searchResultContainer-33ivj > div:nth-child(1) > div.sc-bwzfXH.hFUbDu.sc-bdVaJa.eekvlW > div:nth-child(2) > div.sc-bwzfXH.liBCIH.sc-bdVaJa.eGpriy > div:nth-child(6) > div.icheckbox_minimal-blue > ins',
Party: '#rebass-provider > div > div.Search-root-2gThI > div > div.Search-searchResultContainer-33ivj > div:nth-child(1) > div.sc-bwzfXH.hFUbDu.sc-bdVaJa.eekvlW > div:nth-child(2) > div.sc-bwzfXH.liBCIH.sc-bdVaJa.eGpriy > div:nth-child(8) > div.icheckbox_minimal-blue > ins',
Local: '#rebass-provider > div > div.Search-root-2gThI > div > div.Search-searchResultContainer-33ivj > div:nth-child(1) > div.sc-bwzfXH.hFUbDu.sc-bdVaJa.eekvlW > div:nth-child(2) > div.sc-bwzfXH.liBCIH.sc-bdVaJa.eGpriy > div:nth-child(10) > div.icheckbox_minimal-blue > ins',
Venues: '#rebass-provider > div > div.Search-root-2gThI > div > div.Search-searchResultContainer-33ivj > div:nth-child(1) > div.sc-bwzfXH.hFUbDu.sc-bdVaJa.eekvlW > div:nth-child(2) > div.sc-bwzfXH.liBCIH.sc-bdVaJa.eGpriy > div:nth-child(12) > div.icheckbox_minimal-blue > ins',
Venues: '#rebass-provider > div > div.Search-root-2gThI > div > div.Search-searchResultContainer-33ivj > div:nth-child(1) > div.sc-bwzfXH.hFUbDu.sc-bdVaJa.eekvlW > div:nth-child(2) > div.sc-bwzfXH.liBCIH.sc-bdVaJa.eGpriy > div:nth-child(12) > div.icheckbox_minimal-blue > ins',
Experiences: '#rebass-provider > div > div.Search-root-2gThI > div > div.Search-searchResultContainer-33ivj > div:nth-child(1) > div.sc-bwzfXH.hFUbDu.sc-bdVaJa.eekvlW > div:nth-child(2) > div.sc-bwzfXH.liBCIH.sc-bdVaJa.eGpriy > div:nth-child(14) > div.icheckbox_minimal-blue > ins',
Pickup: 'input[name="startDate"]',
Dropoff: 'input[name="endDate"]',
Rating: '#ratings-picker',
MinPrice: 'input[name="priceMin"]',
MaxPrice: 'input[name="priceMax"]',
SearchBtn: '#rebass-provider > div > div.Search-root-2gThI > div > div.Search-searchResultContainer-33ivj > div:nth-child(1) > div.b-0.bb-1.b-cool-gray-light.mb-l.sc-bwzfXH.hFUbDu.sc-bdVaJa.iHZvIS > div.sc-bwzfXH.dPQNhN.sc-bdVaJa.iHZvIS > div.sc-bwzfXH.jJrIwu.sc-bdVaJa.iHZvIS > button',
ClearBtn: '#rebass-provider > div > div.Search-root-2gThI > div > div.Search-searchResultContainer-33ivj > div:nth-child(1) > div.sc-bwzfXH.hFUbDu.sc-bdVaJa.eekvlW > div.sc-cJSrbW.ipLTMg.sc-TOsTZ.gRZMgn > div > button',
Results: 'li[class="rc-pagination-total-text"]',


}
}